name: docker-release-builds
on:
  schedule:
    # Push the nightly docker daily at 1 PM UTC
    - cron: '0 13 * * *'
  # Trigger when we modify something related to these images
  pull_request:
    paths:
      - Dockerfile
      - docker.Makefile
      - .github/scripts/build_publish_nightly_docker.sh
  # Have the ability to trigger this job manually using the API as well
  workflow_dispatch:

jobs:
  docker-release-build:
    if: ${{ github.repository == 'pytorch/pytorch' }}
    runs-on: linux.2xlarge
    env:
      GHCR_PAT: ${{ secrets.GHCR_PAT }}
      WITH_PUSH: ${{ github.event_name == 'schedule' }}
    steps:
      - name: Checkout
        uses: zhouzhuojie/checkout@05b13c9a0d21f08f6d5e64a1d5042246d13619d9
        with:
          ref: master
      - uses: nick-fields/retry@71062288b76e2b6214ebde0e673ce0de1755740a
        name: Build and upload nightly docker
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: |
            set -ex
            bash .github/scripts/build_publish_nightly_docker.sh

concurrency:
  group: push-nightly-docker-ghcr-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true
